// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTm7JdNeu3suQWPhLISIagRCPuNUoci8',
    appId: '1:729434133966:web:8e63f3615b48f197c7879f',
    messagingSenderId: '729434133966',
    projectId: 'barberapp1-ea227',
    authDomain: 'barberapp1-ea227.firebaseapp.com',
    storageBucket: 'barberapp1-ea227.firebasestorage.app',
    measurementId: 'G-87V9LTSFFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1N1Y9slSYbsiYHWk2DsCXU4hfZg5WM7M',
    appId: '1:729434133966:android:65e73d7a276542e9c7879f',
    messagingSenderId: '729434133966',
    projectId: 'barberapp1-ea227',
    storageBucket: 'barberapp1-ea227.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47f0J1VcXgSppRzfhakU45Ht5goiz_9U',
    appId: '1:729434133966:ios:1f8980f32d5bd7dfc7879f',
    messagingSenderId: '729434133966',
    projectId: 'barberapp1-ea227',
    storageBucket: 'barberapp1-ea227.firebasestorage.app',
    iosBundleId: 'com.example.fun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47f0J1VcXgSppRzfhakU45Ht5goiz_9U',
    appId: '1:729434133966:ios:1f8980f32d5bd7dfc7879f',
    messagingSenderId: '729434133966',
    projectId: 'barberapp1-ea227',
    storageBucket: 'barberapp1-ea227.firebasestorage.app',
    iosBundleId: 'com.example.fun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgTm7JdNeu3suQWPhLISIagRCPuNUoci8',
    appId: '1:729434133966:web:075f13625b7d76ebc7879f',
    messagingSenderId: '729434133966',
    projectId: 'barberapp1-ea227',
    authDomain: 'barberapp1-ea227.firebaseapp.com',
    storageBucket: 'barberapp1-ea227.firebasestorage.app',
    measurementId: 'G-FVM533XG3T',
  );

}